export const CAPITULOS = [
  { id: 'c01', name: 'Sistema Cardiovascular' },
  { id: 'c02', name: 'Sangre y Coagulación' },
  { id: 'c03', name: 'Sistema Gastrointestinal' },
  { id: 'c04', name: 'Sistema Respiratorio' },
  { id: 'c05', name: 'Dolor y Fiebre' },
  { id: 'c06', name: 'Patología Osteoarticular' },
  { id: 'c07', name: 'Sistema Hormonal' },
  { id: 'c08', name: 'Ginecología y Obstetricia' },
  { id: 'c09', name: 'Sistema Urogenital' },
  { id: 'c10', name: 'Sistema Nervioso' },
  { id: 'c11', name: 'Infecciones' },
  { id: 'c12', name: 'Inmunidad' },
  { id: 'c13', name: 'Dermatología' },
  { id: 'c14', name: 'Oftalmología' },
  { id: 'c15', name: 'Otorrinolaringología' },
  { id: 'c16', name: 'Anestésicos' },
  { id: 'c17', name: 'Antídotos y Quelantes' },
  { id: 'c18', name: 'Medicamentos Diversos' },
];
