export const CAPITULOS = [
  { id: '01', name: 'Sistema Cardiovascular' },
  { id: '02', name: 'Sangre y Coagulación' },
  { id: '03', name: 'Sistema Gastrointestinal' },
  { id: '04', name: 'Sistema Respiratorio' },
  { id: '05', name: 'Dolor y Fiebre' },
  { id: '06', name: 'Patología Osteoarticular' },
  { id: '07', name: 'Sistema Hormonal' },
  { id: '08', name: 'Ginecología y Obstetricia' },
  { id: '09', name: 'Sistema Urogenital' },
  { id: '10', name: 'Sistema Nervioso' },
  { id: '11', name: 'Infecciones' },
  { id: '12', name: 'Inmunidad' },
  { id: '13', name: 'Dermatología' },
  { id: '14', name: 'Oftalmología' },
  { id: '15', name: 'Otorrinolaringología' },
  { id: '16', name: 'Anestésicos' },
  { id: '17', name: 'Nutrición y Metabolismo' },
  { id: '18', name: 'Oncología' },
];
